In [1]:
import numpy as np

In [2]:
array = np.arange(1,11)
expon=np.exp(array)

In [3]:
expon

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [4]:
np.set_printoptions(precision=3)
expon

array([2.718e+00, 7.389e+00, 2.009e+01, 5.460e+01, 1.484e+02, 4.034e+02,
       1.097e+03, 2.981e+03, 8.103e+03, 2.203e+04])

In [5]:
np.set_printoptions(precision=3, suppress=True)
expon

array([    2.718,     7.389,    20.086,    54.598,   148.413,   403.429,
        1096.633,  2980.958,  8103.084, 22026.466])

### 参考文献

・[PythonのNumPyモジュールの数値の表示を見やすくする](http://ictsr4.com/sw/python%E3%81%AEnumpy%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB%E3%81%AE%E6%95%B0%E5%80%A4%E3%81%AE%E8%A1%A8%E7%A4%BA%E3%82%92%E8%A6%8B%E3%82%84%E3%81%99%E3%81%8F%E3%81%99%E3%82%8B/)